name: factura24
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  formz: ^0.7.0
  gallery_image_viewer: ^1.2.0
  go_router: ^13.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
